version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - .data:/data/db
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  bot:
    container_name: bot
    restart: always
    build: ./bot
    links:
      - backend